	ORG	00H		;INDICATES THE START OF PROGRAM & IS USED TO SET REGISTER ADDRESS DURING ASSEMBLY
	AJMP	MAIN		;JUMPS TO THE ADDRESS 'MAIN'

MAIN:	MOV	A,#00H
	MOV	P1,A		;CONTROLLING FIRST AND SECOND TRAFFIC LIGHT
	MOV	P2,A		;CONTROLLING THIRD AND FOURTH TRAFFIC LIGHT
	MOV	P3,A		;CONTROLLING THE 7-SEGMENT
 
START:	;FIRST TRAFFIC LIGHT
	MOV	P1,#033H	;GREEN(FIRST) & RED(SECOND) LIGHTS UP
	MOV	P2,#01BH	;RED LIGHTS UP(THIRD & FOURTH)
	ACALL	FIVE		;CALLING IT TO UNDERGO THE SUBROUTINE FIVE
	MOV	P1,#02BH	;GREEN(FIRST) TURNS OFF WHILE YELLOW(FIRST) AND RED(SECOND) LIGHTS UP
	MOV	P2,#01BH	;RED STILL LIGHTS UP(THIRD & FOURTH)
	ACALL	TWO		;CALLING IT TO UNDERGO THE SUBROUTINE TWO
	MOV	P1,#01BH	;YELLOW(FIRST) TURNS OFF WHILE RED(FIRST & SECOND) LIGHTS UP
	MOV	P2,#01BH	;RED STILL LIGHTS UP(THIRD & FOURTH)
	ACALL	ZERO		;CALLING IT TO UNDERGO THE SUBROUTINE ZERO

	;SECOND TRAFFIC LIGHT
	MOV	P1,#01EH	;GREEN(SECOND) LIGHTS UP & RED(FIRST) REMAINS ON
	MOV	P2,#01BH	;RED STILL LIGHTS UP(THIRD & FOURTH)
	ACALL	FIVE		;CALLING IT TO UNDERGO THE SUBROUTINE FIVE
	MOV	P1,#01DH	;GREEN(SECOND) TURNS OFF WHILE YELLOW(SECOND) AND RED(FIRST) LIGHTS UP
	MOV	P2,#01BH	;RED STILL LIGHTS UP(THIRD & FOURTH)
	ACALL	TWO		;CALLING IT TO UNDERGO THE SUBROUTINE TWO
	MOV	P1,#01BH	;YELLOW(SECOND) TURNS OFF WHILE RED(FIRST & SECOND) LIGHTS UP
	MOV	P2,#01BH	;RED STILL LIGHTS UP(THIRD & FOURTH)
	ACALL	ZERO		;CALLING IT TO UNDERGO THE SUBROUTINE ZERO

	;CONTROLLING THIRD TRAFFIC LIGHT
	MOV	P1,#01BH	;RED STILL LIGHTS UP(FIRST & SECOND)
	MOV	P2,#033H	;GREEN(THIRD) LIGHTS UP & RED(FOURTH) REMAINS ON
	ACALL	FIVE		;CALLING IT TO UNDERGO THE SUBROUTINE FIVE
	MOV	P1,#01BH	;RED STILL LIGHTS UP(FIRST & SECOND)
	MOV	P2,#02BH	;GREEN(THIRD) TURNS OFF WHILE YELLOW(THIRD) AND RED(FOURTH) LIGHTS UP
	ACALL	TWO		;CALLING IT TO UNDERGO THE SUBROUTINE TWO
	MOV	P1,#01BH	;RED STILL LIGHTS UP(FIRST & SECOND)
	MOV	P2,#01BH	;YELLOW(THIRD) TURNS OFF WHILE RED(THIRD & FOURTH) LIGHTS UP
	ACALL	ZERO		;CALLING IT TO UNDERGO THE SUBROUTINE ZERO

	;CONTROLLING FOURTH TRAFFIC LIGHT
	MOV	P1,#01BH	;RED STILL LIGHTS UP(FIRST & SECOND)
	MOV	P2,#01EH	;GREEN(FOURTH) LIGHTS UP & RED(THIRD) REMAINS ON
	ACALL	FIVE		;CALLING IT TO UNDERGO THE SUBROUTINE FIVE
	MOV	P1,#01BH	;RED STILL LIGHTS UP(FIRST & SECOND)
	MOV	P2,#01DH	;GREEN(FOURTH) TURNS OFF WHILE YELLOW(FOURTH) AND RED(THIRD) LIGHTS UP
	ACALL	TWO		;CALLING IT TO UNDERGO THE SUBROUTINE TWO
	MOV	P1,#01BH	;RED STILL LIGHTS UP(FIRST & SECOND)
	MOV	P2,#01BH	;YELLOW(FOURTH) TURNS OFF WHILE RED(THIRD & FOURTH) LIGHTS UP
	ACALL	ZERO		;CALLING IT TO UNDERGO THE SUBROUTINE ZERO
	AJMP	START		;JUMPS TO THE ADDRESS 'START'

DELAY:	MOV	R2,#0FFH	;TO DELAY THE FUNCTION
DELAY1:	MOV	R3,#0FFH
DELAY2:	DJNZ	R3,DELAY2
	DJNZ	R2,DELAY1
	DJNZ	R1,DELAY
	RET			;RETURN FROM SUBROUTINE

FIVE:	MOV	P3,#1101110B	;7-SEGMENT WILL DISPLAY '5'
	MOV	R1,#007H	;THE DURATION OF THE DISPLAY
	ACALL	DELAY		;CALLING IT TO UNDERGO THE SUBROUTINE DELAY
	MOV	P3,#1100101B	;7-SEGMENT WILL DISPLAY '4'
	MOV	R1,#007H	;THE DURATION OF THE DISPLAY
	ACALL	DELAY		;CALLING IT TO UNDERGO THE SUBROUTINE DELAY
	MOV	P3,#1001111B	;7-SEGMENT WILL DISPLAY '3'
	MOV	R1,#007H	;THE DURATION OF THE DISPLAY
	ACALL	DELAY		;CALLING IT TO UNDERGO THE SUBROUTINE DELAY
	RET			;RETURN FROM SUBROUTINE

TWO:	MOV	P3,#1011011B	;7-SEGMENT WILL DISPLAY '2'
	MOV	R1,#007H	;THE DURATION OF THE DISPLAY
	ACALL	DELAY		;CALLING IT TO UNDERGO THE SUBROUTINE DELAY
	MOV	P3,#0000101B	;7-SEGMENT WILL DISPLAY '1'
	MOV	R1,#007H	;THE DURATION OF THE DISPLAY
	ACALL	DELAY		;CALLING IT TO UNDERGO THE SUBROUTINE DELAY
	RET			;RETURN FROM SUBROUTINE

ZERO:	MOV	P3,#0111111B	;7-SEGMENT WILL DISPLAY '0'
	MOV	R1,#007H	;THE DURATION OF THE DISPLAY
	ACALL	DELAY		;CALLING IT TO UNDERGO THE SUBROUTINE DELAY
	RET			;RETURN FROM SUBROUTINE

	END			;NO MORE ASSEMBLY LANGUAGE